import {execFile} from 'node:child_process';
import {promisify} from 'node:util';

import {compareUrl} from './apply.js';
import type {Check, PatchFile, Verdict} from './apply.js';

const run = promisify(execFile);

/**
 * The body of the pull request.
 *
 * **No credential goes in it, ever.** Two reasons and either alone is enough: a pull request is
 * frequently public, and putting a key in one is exactly what the redaction pass on the way in
 * exists to prevent.
 *
 * It also avoids the worse failure. `init` mints an `sk_test_` key, and a test key committed into
 * production configuration means an application that deploys, runs, records every send and
 * **delivers nothing** — silently, with everything landing `SENT`. That is the one failure mode
 * test keys are capable of, and a helpful default would walk straight into it. So the body carries
 * the variable NAME and a placeholder; the key itself was printed once in the terminal, for the
 * developer's local `.env`.
 *
 * And it says what was checked. A pull request that ran no checks and does not say so is asking a
 * reviewer to trust something nobody verified.
 */

export interface PullRequestInput {
  verdict: Verdict;
  created: PatchFile[];
  replaced: PatchFile[];
  /** Events the model flagged as uncertain. Named, because a guess that reads as a finding is how
   * a reviewer approves the wrong thing. */
  unsure: {name: string; source: string}[];
  /** Where a live key is made. Never a key. */
  dashboardUrl: string;
}

/** Anything shaped like a real credential. Belt and braces — the server refused these already. */
const CREDENTIAL = /\b(?:sk|pk|rk)_(?:live|test)_[A-Za-z0-9]{16,}|\bwhsec_[A-Za-z0-9+/=_-]{16,}/;

export const PR_TITLE = 'Add transactional emails';

function checksSection(verdict: Verdict): string[] {
  if (verdict.ranNothing) {
    // Loudly. The difference between "checked and fine" and "nothing was run" is the difference
    // between a reviewer skimming this and a reviewer reading it.
    return [
      '### Checks',
      '',
      '> **Nothing was run.** This repository has no `test` script, so the patch below is unverified.',
      '> Read it as a draft.',
    ];
  }

  const line = (check: Check): string => {
    if (check.before && check.after) return `- \`${check.name}\` — passed before and after.`;
    if (!check.before && !check.after) {
      // Named as pre-existing, so nobody spends an afternoon looking for what `init` broke.
      return `- \`${check.name}\` — **was already failing before this branch**, and still is. Not caused by this change.`;
    }

    return `- \`${check.name}\` — passed before, fails now.`;
  };

  return ['### Checks', '', ...verdict.checks.map(line)];
}

export function buildBody(input: PullRequestInput): string {
  const {verdict, created, replaced, unsure, dashboardUrl} = input;

  const lines: string[] = [
    'Generated by [`npx bitelio init`](https://www.npmjs.com/package/bitelio).',
    '',
    '### What changed',
    '',
    ...replaced.map(file => `- \`${file.path}\` — edited.`),
    // Marked, because nobody reviewed these on the consent screen. A reviewer should know which
    // files are new to everyone.
    ...created.map(file => `- \`${file.path}\` — **new file**.`),
    '',
    ...checksSection(verdict),
    '',
    '### Before this works',
    '',
    'Add to your environment:',
    '',
    '```',
    'BITELIO_API_KEY=          # the test key printed in your terminal',
    '```',
    '',
    `A **test key sends nothing.** It does everything a live key does and stops before the provider, so`,
    `every send is recorded and none is delivered — which is what you want while this is in review, and`,
    `not what you want in production. Create a live key at ${dashboardUrl} when you are ready.`,
  ];

  if (unsure.length > 0) {
    lines.push(
      '',
      '### Worth a second look',
      '',
      'These were inferred with low confidence:',
      '',
      ...unsure.map(event => `- \`${event.name}\` — from \`${event.source}\`.`),
    );
  }

  const body = lines.join('\n');

  // The last gate. The server refuses a patch containing a credential and the redaction pass runs
  // on the way in, but this is the text that becomes public, and a check here costs nothing.
  if (CREDENTIAL.test(body)) {
    throw new Error('Refusing to open a pull request whose body contains something shaped like a key.');
  }

  return body;
}

export interface OpenedPullRequest {
  /** The URL of the pull request, when one was opened. */
  url: string | null;
  /** Where to open it by hand, when `gh` could not. Null when even that is unknowable. */
  openManuallyAt: string | null;
  /** Why it was not opened, for the CLI to print. */
  reason: string | null;
}

/**
 * The two outside things this needs, injectable so a test never touches the network.
 *
 * Not a nicety: the first version of the test asserted that `gh` was absent, and on a machine where
 * it is installed and signed in — this one — it went on to attempt a real `git push` to the
 * fictional remote in the fixture. A test that reaches a third party's repository name because of
 * how the developer's laptop happens to be configured is not a test.
 */
export interface PullRequestDeps {
  /** Whether the GitHub CLI is here AND signed in. Both, because installed-but-logged-out is common. */
  ghUsable(repo: string): Promise<boolean>;
  exec(file: string, args: string[], repo: string): Promise<{stdout: string}>;
}

const realDeps: PullRequestDeps = {
  async ghUsable(repo) {
    try {
      await run('gh', ['auth', 'status'], {cwd: repo});

      return true;
    } catch {
      return false;
    }
  },
  async exec(file, args, repo) {
    const {stdout} = await run(file, args, {cwd: repo});

    return {stdout};
  },
};

/**
 * Open the pull request, or say exactly where to open it.
 *
 * Never fails the command. The branch is already committed and is the valuable part; `gh` missing,
 * logged out, or refusing to push is an inconvenience, and a tool that discards a working branch
 * because it could not do the last optional step is a tool nobody runs twice.
 *
 * `execFile` with an argument array, never a shell string — the body is model-derived text with
 * backticks and newlines in it.
 */
export async function openPullRequest(
  repo: string,
  branch: string,
  base: string,
  body: string,
  deps: PullRequestDeps = realDeps,
): Promise<OpenedPullRequest> {
  const manually = compareUrl(repo, branch);

  if (!(await deps.ghUsable(repo))) {
    return {
      url: null,
      openManuallyAt: manually,
      reason: 'The GitHub CLI is not installed or not signed in, so the branch is here and the pull request is not.',
    };
  }

  try {
    await deps.exec('git', ['push', '-q', '--set-upstream', 'origin', branch], repo);
    const {stdout} = await deps.exec(
      'gh',
      ['pr', 'create', '--base', base, '--head', branch, '--title', PR_TITLE, '--body', body],
      repo,
    );

    const url = /https:\/\/github\.com\/\S+/.exec(stdout)?.[0] ?? null;

    return {url, openManuallyAt: url ? null : manually, reason: null};
  } catch (error) {
    return {
      url: null,
      openManuallyAt: manually,
      // The real message: "no upstream", "permission denied", "protected branch" are all different
      // problems with different fixes, and a generic sentence helps with none of them.
      reason: `The branch is committed here; opening the pull request failed: ${(error as Error).message.split('\n')[0]}`,
    };
  }
}
